### ISSUE TITLE
Issue with Octoprint Settings Dialog

### ISSUE THREAD

**Issue by ScottWell1** [jneilliii/OctoPrint-PlotlyTempGraph#49]
When PlotlyTempGraph is enabled, opening the Octoprint Settings dialog (i.e., by clicking the "wrench" in header) brings up the Octoprint Settings dialog, but the dialog's Close and Save buttons do not work.  This prevents making any settings to the native Octoprint Settings, as the SAVE button does not function.  The Close button is non-responsive, but the dialog can be closed using the X at top-right corner. The SAVE button is non-responsive and displays the rotating "busy" symbol in front of the word "Save".
<img width="127" alt="image" src="https://github.com/jneilliii/OctoPrint-PlotlyTempGraph/assets/19198944/27718093-102a-4133-8a4b-918b9bf0c80a">

If I disable PlotlyTempGraph and restart Octoprint, the problem is gone and the Octoprint Settings dialog (both Close and Save buttons) work as expected.  If I again enable PlotlyTempGraph and restart Octorprint, the problem returns.

I am using PlotlyTempGraph 0.1.5 and  Octoprint 1.9.2.  

Could this be related to the settings/template change in 0.1.5?  Maybe a problem with settings retrieval by the addon?  In case it is relevant, I added a manual edit to config.yaml with 0.1.5, creating a custom hover template for the identifier "Exhaust actual".  That works fine (it is displayed correctly on chart), but perhaps there is some syntactical issue?  Replacing that custom template with the default (two single quotes) does _not_ resolve the issue.

The "Exhaust actual" identifier comes from a customized version of the "PlotlyTempGraph_SystemCmds.py" addon in your examples section.  Disabling or uninstalling that addon does _not_ resolve the issue.

Any ideas?

Here are all my PlotlyTempGraph settings from config.yaml:
```
  plotlytempgraph:
    _config_version: 5
    name_map:
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: tool0 actual
      label: tool0 actual
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: tool0 target
      label: tool0 target
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: bed actual
      label: bed actual
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: bed target
      label: bed target
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: chamber actual
      label: chamber actual
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: chamber target
      label: chamber target
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: X actual
      label: Heat Break
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: true
      hover_color: ''
      hover_template: ''
      identifier: X target
      label: ''
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: A actual
      label: Buddy PCB
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: true
      hover_color: ''
      hover_template: ''
      identifier: A target
      label: ''
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: ''
      identifier: Enclosure actual
      label: Enclosure
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      hover_template: <b>%{y:.0f}%</b>
      identifier: Exhaust actual
      label: Exhaust Fan
      use_fahrenheit: false
      use_sub_plot: false
    - color: ''
      hidden: false
      hover_color: ''
      identifier: W actual
      label: ''
      use_fahrenheit: false
      use_sub_plot: false

```
